// Mocks generated by Mockito 5.0.15 from annotations
// in fordevs_enquetes/test/presentation/presenters/stream_login_presenter_test.dart.
// Do not manually edit this file.

import 'package:fordevs_enquetes/presentation/protocols/validation.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [Validation].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidation extends _i1.Mock implements _i2.Validation {
  MockValidation() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String? validate({String? field, String? value}) => (super.noSuchMethod(
          Invocation.method(#validate, [], {#field: field, #value: value}))
      as String?);
  @override
  String toString() => super.toString();
}
